name: Deploy ROSPkgManager
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.20.x'
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
        platform: x64
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.2.1'
        setup-python: false
    
    - name: Install Curl
      run: sudo apt install -y sudo curl libssl-dev libcurl4-openssl-dev

    - name: Build ROSPackageManager
      env:
        CC: gcc-11
        CXX: g++-11 
      run: |
            cmake -Bbuild
            cmake --build build
            mv build/ROSPkgManager build/ROSPackageManager-${{ steps.previoustag.outputs.tag }}

  build-test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
  
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.20.x'

    - name: Install Curl
      run: brew install openssl curl

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.2.1'
        setup-python: false
    - name: Build ROSPackageManager
      run: |
            cmake -Bbuild
            cmake --build build
            mv build/ROSPkgManager.app build/ROSPackageManager-${{ steps.previoustag.outputs.tag }}.app
    
    - uses: actions/upload-artifact@v1
      with:
          name: build-test-macos
          path: build/ROSPkgManager.app

  build-test-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Get Previous tag
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.2.1'
        arch: 'win64_mingw81'

    - name: Upgrade GCC
      run: choco upgrade mingw

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.20.x'

    - name: Build ROSPackageManager
      run: |
            cmake -Bbuild -G "MinGW Makefiles"
            cmake --build build
            mv build/ROSPkgManager.exe build/ROSPackageManager-${{ steps.previoustag.outputs.tag }}.exe
  
    - uses: actions/upload-artifact@v1
      with:
          name: build-test-windows
          path: build/ROSPackageManager-${{ steps.previoustag.outputs.tag }}.exe

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - build-test-windows
      - build-test-macos
      - build-test-linux
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ROSPkgManager Release ${{ steps.previoustag.outputs.tag }}
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          tag_name: ${{ steps.previoustag.outputs.tag }}
          files: |
            build/ROSPackageManager-${{ steps.previoustag.outputs.tag }}.*
