name: Build & Test Linux

on: [push]
jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/checkout@v2
      with:
        repository: Railway-Op-Sim/rostools
        ref: v0.4.0
    - name: Install ROSTools
      run: |
        cmake -Bbuild
        sudo cmake --build build/ --target install
      working-directory: rostools/cpp
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with: 
        version: '5.1.2'
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.20.x'
    - name: Build RailwayBuilder  
      run: |
            cmake -Bbuild
            cmake --build build