name: Build & Test

on: [push]
jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.20.x'
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
        platform: x64
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.2.1'
        setup-python: false
    
    - name: Install Curl
      run: sudo apt install -y sudo curl libssl-dev libcurl4-openssl-dev

    - name: Build ROSPackageManager
      env:
        CC: gcc-11
        CXX: g++-11 
      run: |
            cmake -Bbuild
            cmake --build build
    - uses: actions/upload-artifact@v1
      with:
          name: ubuntu_rospkg
          path: build/ROSPkgManager
  build-test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
  
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.20.x'

    - name: Install Curl
      run: brew install curl

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.2.1'
        setup-python: false
    - name: Build ROSPackageManager
      run: |
            cmake -Bbuild
            cmake --build build
    - uses: actions/upload-artifact@v1
      with:
          name: darwin_rospkg
          path: build/ROSPkgManager.app
  build-test-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install ZLIB
      run: powershell -Command "(Invoke-WebRequest -Uri https://git.io/JnHTY -OutFile install_zlib.bat)"; ./install_zlib.bat; del install_zlib.bat
    
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: >-
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-openssl
    
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      id: setup-mingw
      with:
        platform: x64
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.2.1'
        arch: 'win64_mingw81'  
  
    - name: Build ROSPackageManager 
      run: |
            /mingw64/bin/cmake -Bbuild -G "MinGW Makefiles" -DCMAKE_MAKE_PROGRAM:PATH=/mingw64/bin/mingw64-make -DCMAKE_C_COMPILER=${{ steps.setup-mingw.outputs.gcc }} -DCMAKE_CXX_COMPILER=${{ steps.setup-mingw.outputs.gxx }}
            /mingw64/bin/cmake --build build --config Release 
      shell: msys2 {0}
      env:
        CC: gcc
        CXX: g++
  
    - uses: actions/upload-artifact@v1
      with:
          name: win_rospkg
          path: build/ROSPkgManager.exe
