name: Build & Test

on: [push]
jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        path: rospkgmanager
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.20.x'
    - uses: actions/checkout@v2
      with:
        repository: Railway-Op-Sim/rostools
        ref: v0.4.0
        path: rostools
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
        platform: x64
    - name: Install ROSTools
      env:
        CC: gcc-11
        CXX: g++-11
      run: |
        cmake -Bbuild
        sudo cmake --build build/ --target install
      working-directory: rostools/cpp
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with: 
        version: '5.15.2'
        setup-python: false
    - name: Build ROSPackageManager
      env:
        CC: gcc-11
        CXX: g++-11 
      run: |
            cmake -Bbuild
            cmake --build build
      working-directory: rospkgmanager
    - uses: actions/upload-artifact@v1
      with:
          name: unix_rospkg
          path: rospkgmanager/build/ROSPkgManager
  build-test-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        path: rospkgmanager
    - uses: actions/checkout@v2
      with:
        repository: Railway-Op-Sim/rostools
        ref: v0.4.0
        path: rostools
    - name: Install ZLIB
      run: powershell -Command "(Invoke-WebRequest -Uri https://git.io/JnHTY -OutFile install_zlib.bat)"; ./install_zlib.bat; del install_zlib.bat
    - name: Set up Cygwin
      uses: egor-tensin/setup-cygwin@v3
      with:
        platform: x64
        packages: cmake gcc-g++
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
        cygwin: 1
        cc: 1
    - name: Install ROSTools
      run: |
        mkdir install
        cmake -Bbuild
        cmake --build build/ --target install
      working-directory: rostools/cpp
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with: 
        version: '5.15.2'
        setup-python: false
    - name: Build ROSPackageManager 
      run: |
            cmake -Bbuild
            cmake --build build
      working-directory: rospkgmanager
    - uses: actions/upload-artifact@v1
      with:
          name: win_rospkg
          path: rospkgmanager/build/ROSPkgManager.exe
